name: str(required=True) # letters & spaces
schema_version: str(required=True,matches='^(0|[1-9]\\d*)[\\.](0|[1-9]\\d*)[\\.](0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:[\\.](?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:[\\.][0-9a-zA-Z-]+)*))?$')
type: enum('blueprint', required=True)
description: str(required=True,matches='^[a-zA-Z\\s]*$')
tags: list(str(),required=False)
inputs: list(include('ubinputs'),required=True)
settings: settings(include('ubsetting'),required=False)
outputs: list(include('uboutput'),required=False)
modules: list(include('modules'),required=True)
resource_group: str(required=False)
location: str(required=False)
source: include('source',required=False)
---
modules:
  name: str(required=True,matches='^[a-zA-Z0-9_\\-]*$')
  module_type: enum('terraform', required=True)
  source: include('source',required=True)
  tags: list(str(),required=False)
  injectors: list(include('injectors'),required=False)
  inputs: list(include('ubcomponentinputs'),required=True)
  layer: str(required=False)
  settings: settings(include('ubcomponentsetting'),required=False)
  outputs: list(include('ubcomponentoutput'),required=False)
---
source:
  source_type: enum('git','catalog',required=True)
  git: include('git',required=False)
  catalog: include('catalog',required=False)
---
injectors:
  tft_git_url: str(required=True,matches='^https?:\/\/[-a-zA-Z0-9]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([a-zA-Z0-9-\/]*)$')
  tft_git_token: str(required=False)
  tft_prefix: str(required=False,matches='^[a-zA-Z0-9_\\-]*$')
  injection_type: enum('override','inject',required=True)
  tft_name: enum('ibm','kubernetes',required=True)
  tft_parameters: list(include('UBTFTParameter'),required=True)
---
git:
  git_repo_url: str(required=True,match='(\\w+://)(.+@)*([\\w\\d\\.]+)/*(.*)')
  git_token: str(required=False)
  git_release: str(required=False,match='^(0|[1-9]\\d*)[\\.](0|[1-9]\\d*)[\\.](0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:[\\.](?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:[\\.][0-9a-zA-Z-]+)*))?$')
  git_branch: str(required=False)
  git_repo_folder: str(required=False)
  computed_git_repo_url: str(required=False)
---
catalog:
  catalog_name: str(required=False)
  offering_name: str(required=False)
  offering_version: str(required=False)
  offering_kind: str(required=False)
  catalog_id: str(required=False,match='^[a-zA-Z0-9_\\-]*$')
  offering_id: str(required=False,match='^[a-zA-Z0-9_\\-]*$')
  offering_version_id: str(required=False)
  offering_repo_url: str(required=False)
---
ubinputs:
  name: str(required=True,matches='^[a-zA-Z0-9_\\-]*$')
  value: any(required=False,matches='([^\\$])')
  type: str(required=True,matches='([^\\$].*)')
  description: str(required=False)
  sensitive: bool(required=False)
  immutable: bool(required=False)
  hidden: bool(required=False)
  max_length: int(required=False)
  min_length: int(required=False)
  options: list(str(),required=False)
  required: bool(required=False)
  optional: bool(required=False)
  default: any(required=False)
  use_default: bool(required=False)
  metadata: include('ubmetadata',required=False)
  link: str(required=False)
  source: str(required=False)
  cloud_data_type: str(required=False)
---
ubmetadata:
  type: str(required=False)
  aliases: list(str(),required=False)
  description: str(required=False)
  cloud_data_type: str(required=False)
  default_value: str(required=False)
  secure: bool(required=False)
  hidden: bool(required=False)
  immutable: bool(required=False)
  options: list(str(),required=False)
---
ubsetting:
  name: str(required=True,matches='^[a-zA-Z0-9_\\-]*$')
  value: any(required=True)
  use_default: bool(required=False)
  metadata: include('ubmetadata',required=False)
  link: str(required=False)
---
uboutput:
  name: str(required=True,matches='^[a-zA-Z0-9_\\-]*$')
  value: any(required=True,matches='^([$]module[\\.][A-Za-z\\d_\\-<>]+([\\.]outputs[\\.])[A-Za-z\\d_\\-<>]+$)')
  description: str(required=False)
  type: str(required=False)
  use_default: bool(required=False)
  metadata: include('ubmetadata',required=False)
  link: str(required=False)
---
UBTFTParameter:
  name: str(required=True,matches='^[a-zA-Z0-9_\\-]*$')
  value: any(str(),required=True)
---
ubcomponentinputs:
  name: str(required=True,matches='^[a-zA-Z0-9_\\-]*$')
  value: any(required=True,matches='^([$]((module[\\.])[A-Za-z\\d_\\-<>]+([\\.]outputs[\\.])[A-Za-z\\d_\\-<>]+$|(blueprint[\\.]).[A-Za-z\\d_\\-<>]+$)|([^\\$]))')
  type: str(required=False,matches='^(string)|(number)|(bool)|(list)|(map)|(object)')
  description: str(required=False)
  sensitive: bool(required=False)
  default: any(required=False)
  use_default: bool(required=False)
  metadata: include('ubmetadata',required=False)
  link: str(required=False)
  hidden: bool(required=False)
  required: bool(required=False)
  source: str(required=False)
  options: list(str(),required=False)
  cloud_data_type: str(required=False)
---
ubcomponentsetting:
  name: str(required=True,matches='^[a-zA-Z0-9_\\-]*$')
  value: any(required=True)
  type: str(required=False)
  use_default: bool(required=False)
  metadata: include('ubmetadata',required=False)
  link: str(required=False)
---
ubcomponentoutput:
  name: str(required=True,matches='^[a-zA-Z0-9_\\-]*$')
  description: str(required=False)
  value: any(required=False)
  type: str(required=False)
  use_default: bool(required=False)
  metadata: include('ubmetadata',required=False)
  link: str(required=False)

